### ISSUE TITLE
Citation for the 2015-11-29 license update

### ISSUE THREAD

**Issue by chee** [michelf/sim-daltonism#15]
Hey! great project!!

on your readme you mention Matthew Wickline updated the license to CC4-BY-SA on 2015-11-29, but the only mention of this I can find on the internet is right here on this repository!
Do you happen to have an original source for this update? we'd love to use this algorithm in a project of ours, and CC4-BY-SA is very doable but contacting a defunct resource network is not !!

**Comment by michelf** [comment]
http://colorlab.wickline.org/colorblind/colorlab/engine.js

**Comment by chee** [comment]
Thank you so much, @michelf !!
