### ISSUE TITLE
stopped working after upgrading to catalina

### ISSUE THREAD

**Issue by graphicool** [michelf/sim-daltonism#19]
i love your product, it help me alot to design the app with color blindness taken into consideration. thanks for it!
however, since upgrading my mac it stopped working. i miss it...

![image](https://user-images.githubusercontent.com/33804640/103241636-85783a80-495c-11eb-8024-617de8588ea9.png)
![image](https://user-images.githubusercontent.com/33804640/103241656-91fc9300-495c-11eb-8026-c8cb354c986e.png)

**Comment by graphicool** [comment]
recorded the problem: [Video MP4 (1570x818).mp4.zip](https://github.com/michelf/sim-daltonism/files/5748706/Video.MP4.1570x818.mp4.zip)

**Comment by michelf** [comment]
https://michelf.ca/blog/2019/catalina-authorize-screen-recording/

**Comment by graphicool** [comment]
yes! thank you so much!

**Comment by michelf** [comment]
You're welcome.
