### ISSUE TITLE
Porting to other platforms

### ISSUE THREAD

**Issue by BogdanAlexandru** [michelf/sim-daltonism#3]
Hey, I heard about your app from Ustwo's design handbook.  Awesome piece of software, but it's so unfortunate that it's available only on Apple's platforms :(

Would you be interested in porting it to other platforms? I'm thinking about forking the repo and trying to get it to run on both Windows and Ubuntu in my spare time, so I could use it myself.

Let me know.

**Comment by michelf** [comment]
I won't be doing a Windows or Linux version anytime soon. But it's open source and you are free to port it to other platforms if you feel inclined.
