### ISSUE TITLE
Using over fullscreen apps switches to the desktop

### ISSUE THREAD

**Issue by thecodewarrior** [michelf/sim-daltonism#6]
Using Sim Daltonism over fullscreen apps is difficult as whenever you try to move the viewer it snaps you back to the nearest desktop. The Helium app does this well, so here's their implementation:

https://github.com/JadenGeller/Helium/blob/b35a416376dee7184f788e6ae5736f19890d3ddc/Helium/Helium/HeliumPanelController.swift#L122-L129

```swift
class HeliumPanelController : NSWindowController {
    ...
    private var panel: NSPanel! {
        get {
            return (self.window as! NSPanel)
        }
    }
    ...
    private func setFloatOverFullScreenApps() {
        if NSUserDefaults.standardUserDefaults().boolForKey(UserSetting.DisabledFullScreenFloat.userDefaultsKey) {
            panel.collectionBehavior = [.MoveToActiveSpace, .FullScreenAuxiliary]

        } else {
            panel.collectionBehavior = [.CanJoinAllSpaces, .FullScreenAuxiliary]
        }
    }
    ...
}
```

**Comment by michelf** [comment]
I noticed that too. But I'm pretty sure it used to work before Mojave though, as I spent some time debugging that. And if I test it right now, I can move the window over full screen apps just fine. I remember quite well not being able to move the window over a full-screen app a day or two ago. Maybe it's an intermittent problem?

Note that I'm doing pretty much [the same thing](https://github.com/michelf/sim-daltonism/blob/master/Mac%20App/WindowController.swift#L54) as Helium is doing:

```swift
window?.collectionBehavior = [.canJoinAllSpaces, .fullScreenAuxiliary, .participatesInCycle]
```

I guess I need to investigate the next time I observe this.

**Comment by thecodewarrior** [comment]
I'm currently on a (10 year old) MacBook that only supports up to El Capitan, so that might be it. I would work on it but I don't think I can get XCode on this computer any more (because apple won't let you download old versions of software unless it's in your "already purchased" list for some reason) and even if I could I the latest El Capitan version probably doesn't support newer versions of Swift.

**Comment by thecodewarrior** [comment]
Using v2.0.1 it works perfectly. 

Thank you for the prompt replies by the way. I was pleasantly shocked when you replied after only 20 minutes. Most of the time it takes at least a day for people to reply (I'm even worse though, so I'm kinda a pot calling the kettle black).
